config/routes.rb
Rails.application.routes.draw do
  resources :history_categories
  resources :options
  get 'home/top'
  # 管理画面の設定
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :sizes
  resources :sexes
  devise_for :users, module: :users, controllers: {registrations: 'users/registrations'}
  # devise が生成してくれたownerモデルのコントローラのうち、registrations_controller はこちらでカスタムしたものを使いますよ、という宣言。（registrationsのすべてのメソッドを定義する必要はなく、カスタムしたいものだけを宣言すればよい）
  resources :users, only: [:index, :show]
  resources :courses
  resources :breeds
  resources :histories
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user && user.is_admin?
        can :manage, :all
        can :access, :rails_admin
      elsif user
        can :read, :all
        cannot [:new, :update, :destroy], :all
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs
  belongs_to :size

  mount_uploader :breed_img, BreedImgUploader

  # id順、名前順に並び替える
  default_scope { order(id: :asc, name: :asc) }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :histories
  has_many :options
  belongs_to :size
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  belongs_to :breed
  belongs_to :sex
  has_many :histories
  validates :user_id, presence: true
  validates :name, presence: true
  validates :breed_id, presence: true
  # validates :sex_id, presence: true
  # validates :date, presence: true

  mount_uploader :dog_image, DogImageUploader

end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :dog
  belongs_to :course
  belongs_to :history_category

  has_many :options

  mount_uploader :cut_image, CutImageUploader
end

app/models/history_category.rb
class HistoryCategory < ApplicationRecord
  has_many :histories
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :history
  belongs_to :course
end

app/models/pref.rb
class Pref < ApplicationRecord
  has_many :users
end

app/models/sex.rb
class Sex < ApplicationRecord
  has_many :dogs
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :breeds
  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :lockable, :omniauthable

  has_many :dogs
  belongs_to :pref
end

app/controllers/history_categories_controller.rb
class HistoryCategoriesController < ApplicationController
  before_action :set_history_category, only: [:show, :edit, :update, :destroy]

  # GET /history_categories
  # GET /history_categories.json
  def index
    @history_categories = HistoryCategory.all
  end

  # GET /history_categories/1
  # GET /history_categories/1.json
  def show
  end

  # GET /history_categories/new
  def new
    @history_category = HistoryCategory.new
  end

  # GET /history_categories/1/edit
  def edit
  end

  # POST /history_categories
  # POST /history_categories.json
  def create
    @history_category = HistoryCategory.new(history_category_params)

    respond_to do |format|
      if @history_category.save
        format.html { redirect_to @history_category, notice: 'History category was successfully created.' }
        format.json { render :show, status: :created, location: @history_category }
      else
        format.html { render :new }
        format.json { render json: @history_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /history_categories/1
  # PATCH/PUT /history_categories/1.json
  def update
    respond_to do |format|
      if @history_category.update(history_category_params)
        format.html { redirect_to @history_category, notice: 'History category was successfully updated.' }
        format.json { render :show, status: :ok, location: @history_category }
      else
        format.html { render :edit }
        format.json { render json: @history_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /history_categories/1
  # DELETE /history_categories/1.json
  def destroy
    @history_category.destroy
    respond_to do |format|
      format.html { redirect_to history_categories_url, notice: 'History category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history_category
      @history_category = HistoryCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_category_params
      params.require(:history_category).permit(:name)
    end
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/history_categories_helper.rb
module HistoryCategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/history_categories/_form.html.erb
<%= form_with(model: history_category, local: true) do |form| %>
  <% if history_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history_category.errors.count, "error") %> prohibited this history_category from being saved:</h2>

      <ul>
      <% history_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/history_categories/edit.html.erb
<h1>Editing History Category</h1>

<%= render 'form', history_category: @history_category %>

<%= link_to 'Show', @history_category %> |
<%= link_to 'Back', history_categories_path %>

app/views/history_categories/index.html.erb
<section class="history_categories history_categories-index">

  <%# パンくずリスト %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><%= link_to "HOME", root_path %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= t('.title') %></li>
    </ol>
  </nav>
  <%# / パンくずリスト %>

  <h3><%= t '.title' %></h3>

  <%= link_to t('.new'), new_history_category_path, class: 'btn btn-primary btn-new float-right' %>

  <table class="table index-table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">
          <div class="row">
            <div class="col-6 col-sm-3">
              <%= t('.name') %>
            </div>
          </div>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @history_categories.each do |history_category| %>
        <tr data-href="/history_categories/<%= history_category.id %>">
          <th scope="row">
            <%= history_category.id %>
          </th>
          <td>
            <div class="row">
              <div class="col-6 col-sm-3">
                <%= history_category.name %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/history_categories/new.html.erb
<h1>New History Category</h1>

<%= render 'form', history_category: @history_category %>

<%= link_to 'Back', history_categories_path %>

app/views/history_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @history_category.name %>
</p>

<%= link_to 'Edit', edit_history_category_path(@history_category) %> |
<%= link_to 'Back', history_categories_path %>