config/routes.rb
Rails.application.routes.draw do
  resources :history_categories
  resources :options
  get 'home/top'
  # 管理画面の設定
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :sizes
  resources :sexes
  devise_for :users, module: :users, controllers: {registrations: 'users/registrations'}
  # devise が生成してくれたownerモデルのコントローラのうち、registrations_controller はこちらでカスタムしたものを使いますよ、という宣言。（registrationsのすべてのメソッドを定義する必要はなく、カスタムしたいものだけを宣言すればよい）
  resources :users, only: [:index, :show]
  resources :courses
  resources :breeds
  resources :histories
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user && user.is_admin?
        can :manage, :all
        can :access, :rails_admin
      elsif user
        can :read, :all
        cannot [:new, :update, :destroy], :all
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs
  belongs_to :size

  mount_uploader :breed_img, BreedImgUploader

  # id順、名前順に並び替える
  default_scope { order(id: :asc, name: :asc) }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :histories
  has_many :options
  belongs_to :size
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  belongs_to :breed
  belongs_to :sex
  has_many :histories
  validates :user_id, presence: true
  validates :name, presence: true
  validates :breed_id, presence: true
  # validates :sex_id, presence: true
  # validates :date, presence: true

  mount_uploader :dog_image, DogImageUploader

end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :dog
  belongs_to :course
  belongs_to :history_category

  has_many :options

  mount_uploader :cut_image, CutImageUploader
end

app/models/history_category.rb
class HistoryCategory < ApplicationRecord
  has_many :histories
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :history
  belongs_to :course
end

app/models/pref.rb
class Pref < ApplicationRecord
  has_many :users
end

app/models/sex.rb
class Sex < ApplicationRecord
  has_many :dogs
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :breeds
  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :lockable, :omniauthable

  has_many :dogs
  belongs_to :pref
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: '情報を登録しました。' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: '情報を更新しました。' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:user_id, :name, :breed_id, :sex_id, :birthday, :memo, :dog_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when 'success'
        "alert-success"
      when 'error'
        "alert-danger"
      when 'alert'
        "alert-warning"
      when 'notice'
        "alert-info"
      else
        flash_type.to_s
    end
  end
  
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="field form-group col-md-4">
      <%= form.label :user %>
      <%= form.collection_select :user_id, User.all, :id, :name, { prompt: 'ユーザーを選択' }, class: 'form-control' %>
    </div>

    <div class="field form-group col-md-4">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="field form-group col-md-4">
      <%= form.label :breed %>
      <%= form.grouped_collection_select :breed_id, Size.all, :breeds, :name, :id, :name, { prompt: '犬種を選択' }, class: 'form-control' %>
    </div>

    <div class="field form-group col-md-4">
      <%= form.label :sex %><br>
      <%= form.collection_radio_buttons :sex_id, Sex.all, :id, :name %>
    </div>

    <div class="field form-group col-md-4">
      <%= form.label :birthday %>
      <%= form.date_field :birthday, class: 'form-control' %>
    </div>

    <div class="field form-group col-md-12">
      <%= form.label :memo %>
      <%= form.text_area :memo, class: "form-control" %>
    </div>

    <div class="field form-group col-md-4">
      <%= form.label :dog_image %>
      <%= form.file_field :dog_image, class: 'form-control-file' %>
    </div>

    <div class="actions col-md-12">
      <%= form.submit "登録する", class: "btn btn-primary" %>
    </div>

  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<section class="dogs dogs-index">

  <%# パンくずリスト %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><%= link_to "HOME", root_path %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= t('.title') %></li>
    </ol>
  </nav>
  <%# / パンくずリスト %>

  <h3><%= t '.title' %></h3>

  <%= link_to t('.new'), new_dog_path, class: 'btn btn-primary btn-new float-right' %>

  <table class="table index-table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">
          <div class="row">
            <div class="col-6 col-sm-3">
              <%= t('.name') %>
            </div>
            <div class="col-6 col-sm-3">
              <%= t('.user') %>
            </div>
            <div class="col-12 col-sm-6">
              <%= t('.breed') %>
            </div>
          </div>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @dogs.each do |dog| %>
        <tr data-href="/dogs/<%= dog.id %>">
          <th scope="row">
            <%= dog.id %>
          </th>
          <td>
            <div class="row">
              <div class="col-6 col-sm-3">
                <%= dog.name %>
              </div>
              <div class="col-6 col-sm-3">
                <%= dog.user.name %>
              </div>
              <div class="col-12 col-sm-6">
                <%= dog.breed.name %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<div class="row">

  <div class="col-md-4">
    <strong><%= t('activerecord.attributes.dogs.user') %>：</strong>
    <%= @dog.user.name %>
  </div>

  <div class="col-md-4">
    <strong><%= t('activerecord.attributes.dogs.name') %>：</strong>
    <%= @dog.name %>
  </div>

  <div class="col-md-4">
    <strong><%= t('activerecord.attributes.dogs.breed') %>：</strong>
    <%= @dog.breed.name %>
  </div>

  <div class="col-md-4">
    <strong><%= t('activerecord.attributes.dogs.sex') %>：</strong>
    <%= @dog.sex.name %>
  </div>

  <div class="col-md-4">
    <strong><%= t('activerecord.attributes.dogs.birthday') %>：</strong>
    <%= @dog.birthday %>
  </div>

  <div class="col-md-12">
    <strong><%= t('activerecord.attributes.dogs.memo') %></strong>
    <%= simple_format @dog.memo  %>
  </div>

  <div class="col-md-12">
    <%= image_tag @dog.dog_image_url if @dog.dog_image? %>
  </div>

</div>

<p>（最終更新：<%= @dog.updated_at.strftime('%Y年%m月%d日') %>）</p>

<hr>

<%= link_to '戻る', dogs_path, class: "btn btn-secondary" %>
<%= link_to '編集', edit_dog_path(@dog), class: "btn btn-primary btn-info" %>
<%= link_to '履歴を作成', new_history_path(dog_id: @dog.id), class: "btn btn-primary btn-success" %>
　
<%= link_to '削除', dog_path, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-danger" %>