config/routes.rb
Rails.application.routes.draw do
  resources :history_categories
  resources :options
  get 'home/top'
  # 管理画面の設定
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :sizes
  resources :sexes
  devise_for :users, module: :users, controllers: {registrations: 'users/registrations'}
  # devise が生成してくれたownerモデルのコントローラのうち、registrations_controller はこちらでカスタムしたものを使いますよ、という宣言。（registrationsのすべてのメソッドを定義する必要はなく、カスタムしたいものだけを宣言すればよい）
  resources :users, only: [:index, :show]
  resources :courses
  resources :breeds
  resources :histories
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :lockable, :omniauthable

  has_many :dogs
  belongs_to :pref
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :postal, :pref_id, :city, :address_1, :address_2, :tel)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :breed_id %>
    <%= form.mail_field :breed_id %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.number_field :sex %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :user_image %>
    <%= form.file_field :user_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<section class="users users-index">

  <%# パンくずリスト %>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item" aria-current="page"><%= link_to "HOME", root_path %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= t '.title' %></li>
    </ol>
  </nav>
  <%# / パンくずリスト %>

  <h3><%= t '.title' %></h3>

  <%#= link_to '新規登録', new_user_path, class: 'btn btn-primary btn-new float-right' %>

  <table class="table index-table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">
          <div class="row">
            <div class="col-6 col-sm-3">
              <%= t('.name') %>
            </div>
            <div class="col-6 col-sm-3">
              <%= t('.city') %>
            </div>
            <div class="col-12 col-sm-6">
              <%= t('.tel') %>
            </div>
          </div>
        </th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr data-href="/users/<%= user.id %>">
          <th scope="row">
            <%= user.id %>
          </th>
          <td>
            <div class="row">
              <div class="col-6 col-sm-3">
                <%= user.name %>
              </div>
              <div class="col-6 col-sm-3">
                <%= user.city %>
              </div>
              <div class="col-12 col-sm-6">
                <%= user.tel %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</section>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>ユーザー情報</h1>
<hr>
<p>
  <strong><%= t 'activerecord.attributes.user.name' %>： </strong>
  <%= @user.name %>
</p>
<p>
  <strong><%= t 'activerecord.attributes.user.email' %>： </strong>
  <%= @user.email %>
</p>
<p>
  <strong><%= t 'activerecord.attributes.user.postal' %>： </strong>
  <%= @user.postal %>
</p>
<p>
  <strong><%= t 'activerecord.attributes.user.pref' %>： </strong>
  <%= @user.pref.name if @user.pref %>
</p>
<p>
  <strong><%= t 'activerecord.attributes.user.city' %>： </strong>
  <%= @user.city %>
</p>
<p>
  <strong><%= t 'activerecord.attributes.user.address_1' %>： </strong>
  <%= @user.address_1 %>
</p>
<p>
  <strong><%= t 'activerecord.attributes.user.address_2' %>： </strong>
  <%= @user.address_2 %>
</p>
<p>
  <strong><%= t 'activerecord.attributes.user.tel' %>： </strong>
  <%= @user.tel %>
</p>

<br>
<p>
  <strong><%= @user.name %>さんの愛犬</strong>
</p>

<% if @user.dogs.present? %>
  <div class="row dogs-index">
    <% @user.dogs.each do |dog| %>
      <%= link_to dog, class: 'col-12 col-sm-6 col-md-4 col-lg-3' do %>
        <ul class='list-group'>
          <li class="list-group-item">
          <%= t('activerecord.attributes.dogs.name') %>：
            <%= dog.name %>
          </li>
          <li class="list-group-item">
            <%= t('activerecord.attributes.dogs.user') %>：
            <%= dog.user.name %>
          </li>
          <li class="list-group-item">
            <%= dog.breed.name %>
          </li>
          <li class="list-group-item">
            <%= dog.sex.name %>
          </li>
          <li class="list-group-item">
            <%= image_tag dog.dog_image.thumb.url if dog.dog_image? %>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
<% else %>
  <h6>まだ登録されていません。</h6>
<% end %>

<hr>

<%= link_to '戻る', dogs_path, class: "btn btn-secondary" %>
<%= link_to "愛犬を登録", new_dog_path, class: "btn btn-info" %>
<% if current_user == @user %>
  <%= link_to 'ユーザー情報編集', edit_user_registration_path, class: "btn btn-primary" %> 
<% end %>

<% if signed_in? && current_user.is_admin %>
  <%= link_to 'ユーザー情報編集(管理者ページ)', "/admin/user/#{@user.id}", class: "btn btn-primary" %> 
<% end %>