config/routes.rb
Rails.application.routes.draw do
  resources :history_categories
  resources :options
  get 'home/top'
  # 管理画面の設定
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :sizes
  resources :sexes
  devise_for :users, module: :users, controllers: {registrations: 'users/registrations'}
  # devise が生成してくれたownerモデルのコントローラのうち、registrations_controller はこちらでカスタムしたものを使いますよ、という宣言。（registrationsのすべてのメソッドを定義する必要はなく、カスタムしたいものだけを宣言すればよい）
  resources :users, only: [:index, :show]
  resources :courses
  resources :breeds
  resources :histories
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user && user.is_admin?
        can :manage, :all
        can :access, :rails_admin
      elsif user
        can :read, :all
        cannot [:new, :update, :destroy], :all
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs
  belongs_to :size

  mount_uploader :breed_img, BreedImgUploader

  # id順、名前順に並び替える
  default_scope { order(id: :asc, name: :asc) }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :histories
  has_many :options
  belongs_to :size
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  belongs_to :breed
  belongs_to :sex
  has_many :histories
  validates :user_id, presence: true
  validates :name, presence: true
  validates :breed_id, presence: true
  # validates :sex_id, presence: true
  # validates :date, presence: true

  mount_uploader :dog_image, DogImageUploader

end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :dog
  belongs_to :course
  belongs_to :history_category

  has_many :options

  mount_uploader :cut_image, CutImageUploader
end

app/models/history_category.rb
class HistoryCategory < ApplicationRecord
  has_many :histories
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :history
  belongs_to :course
end

app/models/pref.rb
class Pref < ApplicationRecord
  has_many :users
end

app/models/sex.rb
class Sex < ApplicationRecord
  has_many :dogs
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :breeds
  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :lockable, :omniauthable

  has_many :dogs
  belongs_to :pref
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/sexes_helper.rb
module SexesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<%# パンくずリスト %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">HOME</li>
  </ol>
</nav>
<%# / パンくずリスト %>

<%# 管理者アカウントでログインしているとき %>
<% if signed_in? && current_user.is_admin %>

  <h3><%= t('.title-admin') %></h3>
  <hr>

  <div class="row home-top">
    <div class="col-md-4 col-6">
      <%= link_to t('users.index.title'), users_path, class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-md-4 col-6">
      <%= link_to t('dogs.index.title'), dogs_path, class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-md-4 col-6">
      <%= link_to t('histories.index.title'), histories_path, class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-md-4 col-6">
      <%= link_to t('courses.index.title'), courses_path, class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-md-4 col-6">
      <%= link_to t('breeds.index.title'), breeds_path, class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-md-4 col-6">
      <%= link_to t('sizes.index.title'), sizes_path, class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-md-4 col-6">
      <%= link_to t('sexes.index.title'), sexes_path, class: 'btn btn-info btn-block' %>
    </div>
    <div class="col-md-4 col-6">
      <%= link_to t('history_categories.index.title'), history_categories_path, class: 'btn btn-info btn-block' %>
    </div>
  </div>

<%# 一般アカウントでログインor未ログインのとき %>
<% else %>

  <h3><%= t('.title-user') %></h3>
  <hr>
  <p>
    ドッグサロン「DogSalon」のお客様用ページへようこそ！
  </p>
  <p>
    ここでは愛するワンちゃんのトリミング履歴が確認できます。
  </p>

<% end %>